### ISSUE TITLE
redis-service.yaml

### ISSUE THREAD

**Issue by ljshwyykl** [ljshwyykl/blog#16]
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: dev
  labels:
    app: redis
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          command: ["redis-server"]
          ports:
            - containerPort: 6379

---
kind: Service
apiVersion: v1
metadata:
  name: redis-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      # nodePort: 6379
      name: redis

```
