### ISSUE TITLE
clickhouse.yaml

### ISSUE THREAD

**Issue by ljshwyykl** [ljshwyykl/blog#20]
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: clickhouse
  name: clickhouse
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - image: clickhouse/clickhouse-server
          imagePullPolicy: IfNotPresent
          name: clickhouse
          securityContext:
            runAsUser: 501
          ports:
            - containerPort: 8123
              protocol: TCP
          # resources:
          #   limits:
          #     cpu: 1048m
          #     memory: 2Gi
          #   requests:
          #     cpu: 1048m
          #     memory: 2Gi
          volumeMounts:
            - mountPath: /var/lib/clickhouse
              name: clickhouse-volume
      volumes:
        - name: clickhouse-volume
          hostPath:
            path: ~/clickhouse/db
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: dev
spec:
  ports:
    - port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    app: clickhouse
  type: NodePort

```
