### ISSUE TITLE
mongo-service.yaml

### ISSUE THREAD

**Issue by ljshwyykl** [ljshwyykl/blog#21]
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: dev
  labels:
    app: mongo
spec:
  serviceName: mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: xx // current id
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: dir-volume
              mountPath: /data/db
      volumes:
        - name: dir-volume
          hostPath:
            path: xxx
            type: DirectoryOrCreate

---
kind: Service
apiVersion: v1
metadata:
  name: mongo-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo

```
