### ISSUE TITLE
grafana-service.yaml

### ISSUE THREAD

**Issue by ljshwyykl** [ljshwyykl/blog#23]
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: dev
  labels:
    app: grafana
spec:
  serviceName: grafana-service
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: prometheus
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"

---
kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      name: grafana

```
