### ISSUE TITLE
console-service.yaml

### ISSUE THREAD

**Issue by ljshwyykl** [ljshwyykl/blog#24]
kafak ui
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: dev
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: docker.redpanda.com/vectorized/console:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: "192.168.106.1:9092"
---
kind: Service
apiVersion: v1
metadata:
  name: console-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: console
  ports:
    - port: 8080
      targetPort: 8080
      # nodePort: 6379
      name: console

```
